Fix xkb layouts saved as ibus sources
elementary/switchboard-plug-keyboard pull request #338
Opened 2020-11-27 18:31 UTC by jeremypw

Fixes https://github.com/elementary/wingpanel-indicator-keyboard/issues/80

* Move to InputSources directory
* Rename to help distinguish input source and xkb layout
* Some simplification
* Ensure Object () first statement in constructor
* Fix some long lines

The cause of the issue not yet identified but after this refactoring I have not been able to reproduce it again.

2020-12-05 00:45 UTC, ryonakano reviewed
Confirmed the issue fixes.

2020-12-05 00:45 UTC, ryonakano commented on src/Widgets/Layout/Display.vala
> +public class LayoutPage.Display : Gtk.Frame {
We might want to add indentation from L22 to L198.

2020-12-05 12:36 UTC, jeremypw commented on src/Widgets/Layout/Display.vala
> +public class LayoutPage.Display : Gtk.Frame {
I can't remember why I split out the namespace now ... I have reverted that and it still compiles.  Thanks for the review.

2020-12-05 17:54 UTC, tintou commented
Don't forget to update the POTFILES if you rename some files

2020-12-27 12:30 UTC, ryonakano requested changes
There seems to be a regression that you can't add variants of a layout, e.g. if you already set up jp keyboard and try to adding jp+dvorak, nothing happens.

2021-01-02 08:25 UTC, ryonakano approved these changes
This fixes the linked issue and no regressions found. Thank you! :tada:

2021-01-02 15:34 UTC, merged