Adding Multitasking View to Super Key Options
elementary/switchboard-plug-keyboard pull request #400
Opened 2022-03-02 00:44 UTC by MobileAZN

Adding the ability for the Super key to also show the Multitasking View.

2022-03-02 14:32 UTC, davidmhewitt requested changes
There's a minor issue with the current code (I've left a comment inline), then it'll need a review from the UX team to decide if this is a feature that should be implemented in this way.

2022-03-02 14:32 UTC, davidmhewitt commented on src/Views/Layout.vala
> +                case "show-desktop":
```suggestion
                case "dbus-send --session --dest=org.pantheon.gala --print-reply /org/pantheon/gala org.pantheon.gala.PerformAction int32:1":
```

This string needs to match the command you use further down. It's responsible for reading the GSetting and selecting the correct item in the combobox (i.e. on startup). So you'll probably find that your new Multitasking View item is not automatically selected when you restart switchboard after selecting it.

2022-03-02 15:18 UTC, MobileAZN commented on src/Views/Layout.vala
> +                case "show-desktop":
Updated line 217 to match.

2022-03-04 02:40 UTC, cassidyjames commented
UX-wise I think it makes sense to offer the multitasking view as an option for Super, especially because I've heard the desire from GNOME converts. I'll leave the code review to @elementary/desktop-developers though.

2022-03-04 02:41 UTC, cassidyjames reviewed
UX-wise I think it makes sense to offer the multitasking view as an option for Super, especially because I've heard the desire from GNOME converts. I'll leave the code review to @elementary/desktop-developers though.

2022-03-04 10:39 UTC, jeremypw commented
I do not like that a long and complicated string is written out explicitly twice, although a similar style is used in existing code.

2022-03-21 16:10 UTC, davidmhewitt requested changes
> I do not like that a long and complicated string is written out explicitly twice, although a similar style is used in existing code.

Yeah, I'm inclined to agree, can we have the command string brought out into a constant?

Something like `private const string MULTITASKING_COMMAND = "..."` at the top of the class, and then use that constant instead of writing it out twice.

2022-03-28 02:32 UTC, MobileAZN commented
I have updated this to the suggested constant and cleaner call.

2022-03-28 14:49 UTC, davidmhewitt requested changes
elementary code style is to use `UPPERCASE_UNDERSCORE_NAMING` for constants, so I've left those changes as a suggestion.

2022-03-28 14:49 UTC, davidmhewitt commented on src/Views/Layout.vala
> +        private const string MultitaskingView = "dbus-send --session --dest=org.pantheon.gala --print-reply /org/pantheon/gala org.pantheon.gala.PerformAction int32:1";
```suggestion
        private const string MULTITASKING_VIEW_COMMAND = "dbus-send --session --dest=org.pantheon.gala --print-reply /org/pantheon/gala org.pantheon.gala.PerformAction int32:1";
```

2022-03-28 14:49 UTC, davidmhewitt commented on src/Views/Layout.vala
> +                case MultitaskingView:
```suggestion
                case MULTITASKING_VIEW_COMMAND:
```

2022-03-28 14:49 UTC, davidmhewitt commented on src/Views/Layout.vala
> +                    gala_behavior_settings.set_string ("overlay-action", MultitaskingView);
```suggestion
                    gala_behavior_settings.set_string ("overlay-action", MULTITASKING_VIEW_COMMAND);
```

2022-03-28 18:53 UTC, MobileAZN commented
ah, ok.  Updated using the sane defaults you offered @davidmhewitt

2022-03-30 11:43 UTC, davidmhewitt commented
This is looking good now, but I'm going to mark it as blocked until we get https://github.com/elementary/gala/pull/1393 merged. I don't think this option should be available until it's also possible for the multitasking view to be closed with another press of the super key. So we'll await the status of that PR.

2022-03-30 11:49 UTC, davidmhewitt approved these changes
Thanks for your work on this!

2022-03-30 11:50 UTC, merged

2022-03-30 14:14 UTC, MobileAZN commented
haha!  That was my next question, is where do I look to be able to close it with the same key vs hitting esc, as that was the next thing I wanted to look at.  Thanks again for the help!