Layout: modernize the layouts list
elementary/switchboard-plug-keyboard pull request #465
Opened 2023-08-17 05:45 UTC by lenemter

![image](https://github.com/elementary/switchboard-plug-keyboard/assets/80143868/15a6e114-cf5e-4e71-a0d3-e0a98ef498be)

Changes:
- Use `Gtk.ListBox` instead of `Gtk.TreeView`
- Add margins to the items in the box
- Move "Remove", "Move up/down" buttons to the rows

2023-08-17 17:11 UTC, danirabbit requested changes
Nice! Love actions on the rows themselves, much more clear which row will be affected.

It looks like the arrow buttons aren't being set as insensitive when an item is at the top or bottom of the list. For example:
![Screenshot from 2023-08-17 10 04 03](https://github.com/elementary/switchboard-plug-keyboard/assets/7277719/0a28af25-831d-42d3-b366-537226a67e73)

Is there a reason you decided to ditch the list model? That can still be used with ListBox and would probably save some effort manually destroying and rebuilding the list when the model changes

2023-08-17 17:11 UTC, danirabbit commented on src/Widgets/Layout/Display.vala
> +        scroll.add (list);
while we're here can we use `child` property for Gtk4 future proofing?

2023-08-17 17:11 UTC, danirabbit commented on src/Widgets/Layout/Display.vala
> +            warning ("Row activated");
leftover from debugging?

2023-08-17 17:11 UTC, danirabbit commented on src/Widgets/Layout/Display.vala
> +                    halign = END
I don't think these `haligns` have any affect since you're already expanding the label

2023-08-22 11:04 UTC, lenemter commented
> Is there a reason you decided to ditch the list model?

I think the reason why it originally used a model is because of `Gtk.TreeView`, and it didn't save the code from manual rebuilding the tree :) I do agree that using the list model will save some effort but it can be added later if needed.

2023-08-29 16:38 UTC, danirabbit approved these changes
Nice work!

2023-08-29 16:39 UTC, merged