CustomShortcutListBox: use event controllers
elementary/switchboard-plug-keyboard pull request #479
Opened 2023-10-17 18:15 UTC by danirabbit

2023-10-18 09:54 UTC, jeremypw requested changes
When first opened, the custom shortcut displayed is the "default" one (Shift+Ctrl+Alt+F10) not the actual shortcut.  Also keeping references to the controllers seems unnecessary.

2023-10-18 09:54 UTC, jeremypw commented on src/Widgets/Shortcuts/CustomShortcutListBox.vala
> +        private Gtk.GestureMultiPress status_controller;
It does not seem to be necessary to keep these references - you can just use `var`.

2023-10-18 10:01 UTC, jeremypw commented on src/Widgets/Shortcuts/CustomShortcutListBox.vala
> +                keycap_stack.visible_child = keycap_stack;
```suggestion
                keycap_stack.visible_child = keycap_grid;
```

A stack cannot be its own child!

2023-10-18 22:47 UTC, danirabbit commented on src/Widgets/Shortcuts/CustomShortcutListBox.vala
> +                keycap_stack.visible_child = keycap_stack;
Woops, thank you. I thought I fixed this :sweat_smile:

2023-10-18 22:51 UTC, danirabbit commented on src/Widgets/Shortcuts/CustomShortcutListBox.vala
> +        private Gtk.GestureMultiPress status_controller;
In my testing the controllers don't seem to work at all unless we hold a ref to them in GTK 3

2023-10-19 13:21 UTC, jeremypw commented on src/Widgets/Shortcuts/CustomShortcutListBox.vala
> +        private Gtk.GestureMultiPress status_controller;
I'll check again - I may have only tested for compilability.

2023-10-19 13:39 UTC, merged