Port to GTK 4
elementary/switchboard-plug-keyboard pull request #480
Opened 2023-10-19 16:10 UTC by danirabbit

Closes #412

2023-10-20 17:09 UTC, danirabbit commented on src/Dialogs/ProgressDialog.vala
> +            margin_end = 12,
Double check this is right

2024-01-16 21:43 UTC, danirabbit commented on src/InputSources/SourceSettings.vala
> +    public unowned GLib.List<InputSource> input_sources { get; private set; }
Maybe better to add get length method?

2024-01-16 21:43 UTC, danirabbit commented on src/Shortcuts/Shortcut.vala
> -        if ((modifiers & Gdk.ModifierType.MOD2_MASK) > 0) {
These don't exist in Gdk anymore :shrug:

2024-01-18 16:15 UTC, jeremypw commented on src/Dialogs/ConflictDialog.vala
> +        reassign_button.get_style_context ().add_class (Granite.STYLE_CLASS_DESTRUCTIVE_ACTION);
Use `.add_css_class ()` ?

2024-01-18 16:16 UTC, jeremypw commented on src/Dialogs/ProgressDialog.vala
> +        primary_label.get_style_context ().add_class (Granite.STYLE_CLASS_TITLE_LABEL);
Use `add_css_class ()` ?

2024-01-18 16:32 UTC, jeremypw commented on src/Shortcuts/Shortcut.vala
> -        if ((modifiers & Gdk.ModifierType.MOD2_MASK) > 0) {
What about META_MASK, which exists in Gdk4?

2024-01-18 16:36 UTC, jeremypw commented on src/Widgets/InputMethod/AddEnginesPopover.vala
> +        add_button.get_style_context ().add_class (Granite.STYLE_CLASS_SUGGESTED_ACTION);
`add_css_class ()`?

2024-01-18 17:14 UTC, jeremypw commented
Adding and removing layouts and input engines seems to work OK except that adding an input engine (Japanese Anthy)  and immediately removing it invalidates the installed keyboard layout (English (UK)) - however master has the same issue.  Shortcuts seems to work OK except cannot use `Fn` as modifier for custom shortcuts.  I cannot check whether `master` has the same problem as Custom Shortcuts has stopped working there.   

The cursor blinking scale seems to operate the unexpected way?  Increase the value slows the speed of blinking even thought the header is "Speed" - but this is the same as master.  The duration scale did not have a noticeable effect - same as master.  Maybe reconsider the wording of the labels e.g. "Interval on" and "Interval off"?

Sound setings hyperlink not working - presumably because not ported yet.

2024-01-18 17:14 UTC, jeremypw requested changes
In "Behaviour" clicking on the Hyperlink to Onboard settings works but also throws an error dialog "Could not show link - launched failed" - this issue is not present in master.

2024-01-18 18:04 UTC, danirabbit commented
@jeremypw thanks for the review! For any issues that also exist in master could you open issue reports please? This is just a port and doesn't really seek to solve existing issues.

Sound settings link is working here. Do you have the `io.elementary.settings.sound` installed?

Fixed the linkbutton issue!

2024-01-18 18:55 UTC, jeremypw commented
> o you have the io.elementary.settings.sound installed?

Ah, no.  That would explain it!

2024-01-18 18:57 UTC, jeremypw approved these changes

2024-01-18 18:57 UTC, merged